assert(SMODS.load_file("src/jokers.lua"))()
assert(SMODS.load_file("src/enhancements.lua"))()
assert(SMODS.load_file("src/seals.lua"))()
assert(SMODS.load_file("src/twisted_tarots.lua"))()
assert(SMODS.load_file("src/monster.lua"))()
assert(SMODS.load_file("src/editions.lua"))()