assert(SMODS.load_file("src/jokers.lua"))()
assert(SMODS.load_file("src/enhancements.lua"))()
assert(SMODS.load_file("src/seals.lua"))()
assert(SMODS.load_file("src/reverse_tarots.lua"))()
-- assert(SMODS.load_file("src/sounds.lua"))()